version: '3'

services:
  web:
    build: 
      context: .  # where are the files and folders for the image to be pulled from
      dockerfile: Dockerfile.dev  # specify the Dockerfile
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules # ignore node_modules mapping
      - .:/app # map current folder outside container to workdir

  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["yarn", "run", "test"]
