version: '3'

services:
  web:
    build: .
    ports: 
      - "3000:3000"
    volumes:
      - /app/node_modules # ignore node_modules mapping
      - .:/app # map current folder outside container to workdir
